package cn.edu.cqu.graphics.ui.form;

import cn.edu.cqu.graphics.config.PlatformConfig;
import cn.edu.cqu.graphics.platform.PlatformGlobalManager;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.util.logging.Logger;

@Component
public class PreferenceForm extends JFrame {

    PlatformConfig config;

    private JCheckBox enableDiskCacheCheckBox;
    private JButton cancelButton;
    private JButton OKButton;
    private JButton applyButton;
    private JPanel container;

    @Autowired
    private Logger logger;

    @Autowired
    public PreferenceForm(PlatformConfig config) {
        this.config = config;
        init();
    }

    public void init() {
        initWindow();
        initEvent();
    }

    private void initWindow() {
        Dimension dimen = Toolkit.getDefaultToolkit().getScreenSize();
        setSize(new Dimension((int) (dimen.getWidth() * 0.5), (int) (dimen.getHeight() * 0.5)));
        setContentPane(container);
        enableDiskCacheCheckBox.setSelected(config.getEnableCache());
    }

    private void initEvent() {
        cancelButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                PreferenceForm.this.setVisible(false);
            }
        });
        applyButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                config.setEnableCache(enableDiskCacheCheckBox.isSelected());
                try {
                    saveConfig();
                } catch (IOException e1) {
                    e1.printStackTrace();
                    JOptionPane.showMessageDialog(PreferenceForm.this, e1.getMessage());
                }
            }
        });
        OKButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                config.setEnableCache(enableDiskCacheCheckBox.isSelected());
                try {
                    saveConfig();
                } catch (IOException e1) {
                    e1.printStackTrace();
                    JOptionPane.showMessageDialog(PreferenceForm.this, e1.getMessage());
                }
                PreferenceForm.this.setVisible(false);
            }
        });

    }

    private void saveConfig() throws IOException {
        PlatformGlobalManager.cachePlatformConfig(config, logger);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        container = new JPanel();
        container.setLayout(new GridBagLayout());
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridBagLayout());
        panel1.setMaximumSize(new Dimension(2147483647, 48));
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        container.add(panel1, gbc);
        cancelButton = new JButton();
        cancelButton.setText("Cancel");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.weightx = 0.33;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(cancelButton, gbc);
        applyButton = new JButton();
        applyButton.setText("Apply");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.weightx = 0.33;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(applyButton, gbc);
        OKButton = new JButton();
        OKButton.setPreferredSize(new Dimension(102, 48));
        OKButton.setText("OK");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 0.33;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(OKButton, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        container.add(spacer1, gbc);
        enableDiskCacheCheckBox = new JCheckBox();
        enableDiskCacheCheckBox.setText("Enable Disk Cache");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        container.add(enableDiskCacheCheckBox, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return container;
    }
}
